# Generated by Django 5.0 on 2023-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0002_liketype_participateauction_posthashtag_reporttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='users/%Y/%m'),
        ),
    ]
